[package]
name = "git-find-rs"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
anyhow = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
tempfile = "3.10.1"
